name: Masters in Urbanism Studies
favicon: null
layout_spectrum: 0.49789
typography_spectrum: 0.25828
title: 'Masters Program in Urbanism Studies at KTH Royal Institute of Technology, Stockholm'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0353ac'
    - '#9fc7de'
    - '#000000'
    - '#2f2f2f'
  brandStrength: 0.5
  lightness: 0.7299622420687228
  saturation: 0.4401825852692127
  rhythmicContrast: 0.4351970632560551
purpose: []
