name: Masters in Urbanism Studies
favicon: null
layout_spectrum: 0.50391
typography_spectrum: 0.50271
title: 'Masters Program in Urbanism Studies at KTH Royal Institute of Technology, Stockholm'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020731'
    - '#3862c6'
    - '#ae956d'
    - '#ffffff'
    - '#dcd9cf'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
