name: Masters in Urbanism Studies
favicon: null
layout_spectrum: 0.25246
typography_spectrum: 0.9379086252301931
title: 'Masters Program in Urbanism Studies at KTH Royal Institute of Technology, Stockholm'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.23212796030566096
  lightness: 0.7299622420687228
  saturation: 0.4401825852692127
  rhythmicContrast: 0.4351970632560551
purpose: []
